apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-cni-benchmark
    run: ssh-srv
  name: ssh-srv
spec:
  initContainers:
  - image: infrabuilder/netbench:server-ssh
    name: junk-data
    command:
    - /bin/bash
    - -c
    - |
      if [ ! -f /data/10G.dat ]; then
        echo "Generating junk data"
        dd bs=1M if=/dev/urandom of=/data/10G.dat count=10000
      fi
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - image: infrabuilder/netbench:server-ssh
    name: sshd-srv
    volumeMounts:
    - name: data
      mountPath: /root
  volumes:
  - name: data
    hostPath:
      path: /data/test
  nodeSelector:
    kubernetes.io/hostname: s02
  restartPolicy: Never
